"""add language to posts

Revision ID: db0d3761a23c
Revises: d2f4167b2bcd
Create Date: 2018-05-16 17:27:45.169419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db0d3761a23c'
down_revision = 'd2f4167b2bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    op.drop_column('user', 'language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language', sa.VARCHAR(length=5), nullable=True))
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
